### ISSUE TITLE
Support for Ruby Projects

### ISSUE THREAD

**Issue by j-collier** [opencollective/backyourstack#60] opened 2018-08-13 15:56 UTC
Can we add support for Ruby projects by analyzing Gemfiles? Ruby and Ruby on Rails project power huge portions of many companies software applications and adding support for them would be a great asset.

**Comment by znarf** [comment] 2018-08-13 20:46
Would be great to have indeed! It should not be too difficult introducing a 'Gemfile' parser.

Because it's not json, it will be a little bit more difficult than `composer` and `npm`, but nothing extraordinary difficult.

Someone up for it?

**Comment by j-collier** [comment] 2018-08-13 21:01
I can take it if that helps

**Comment by znarf** [comment] 2018-08-14 09:38
@j-collier would be awesome! Let me know if I can help.

**Comment by marcandre** [comment] 2018-08-18 19:09
I imagine the plan to parse `Gemfile.lock`, not `Gemfile`, right?

@j-collier let me know if you don't get around tackling it, I could do it.

**Comment by reedloden** [comment] 2018-08-20 10:03
You can use this module to parse a `Gemfile.lock` file:
https://www.npmjs.com/package/gemfile
https://github.com/treycordova/gemfile

**Comment by znarf** [comment] 2018-08-20 14:28
@marcandre I'm not a Ruby expert but I assume `Gemfile.lock` is not always there and that we would need to support `Gemfile` too?

@reedloden The library looks great! Would be even greater if it could parse `Gemfile` too. 

We made a few changes in the codebase and I think from now it should be even easier to support new languages. We just merged `C#` for example: https://github.com/opencollective/backyourstack/pull/56

**Comment by marcandre** [comment] 2018-08-20 17:41
@znarf The problem is that `Gemfile` is actually a Ruby executable file. So it seems to me to be quite difficult to actually handle any generic `Gemfile`. As such, short of actually running it (would require a VM of some sort), or hack something with a parsing library or Opal, the `.lock` file is the way to go. Note that for gems in particular, there's no information in the `Gemfile` proper, it mostly just refers to `some_gem.gemspec` for example. Indeed the `Gemfile.lock` might not be committed in the repository (it usually is for an app, and isn't for a gem), but any developper will have a `Gemfile.lock` on their computer.

**Comment by j-collier** [comment] 2018-08-20 18:14
I agree that parsing `Gemfile.lock` would be the right way to handle this.

@marcandre take it away if you're feeling inclined!

**Comment by znarf** [comment] 2018-08-20 18:44
@marcandre @j-collier  great, let's support with `Gemfile.lock` then! 

One important thing for the implementation, is `Gemfile.lock` always at the root of the repository or can it be found deeper in the tree? For `composer.json` and `package.json`, we assume it's always at the root while for `.csproj` (C#) we search deeper.

**Comment by marcandre** [comment] 2018-08-20 19:52
It should be safe to assume it's at the root.

@j-collier ok, I'll take a stab at it then.

**Closed** 2018-09-03 07:59 UTC
