### ISSUE TITLE
Logo on white background

### ISSUE THREAD

**Issue by kof** [opencollective/backyourstack#42] opened 2018-07-06 10:10 UTC
I have this white/transparent logo on the open collective page https://opencollective.com/jss. It looks ok there, but now on backyourstack its invisible)

Previously I used to have this logo on the opencollective site: "https://raw.githubusercontent.com/jsstyles/logo/master/logo.png" but then after redesign some time ago it looked broken, so I had to replace it with the white/transparent one.

My project is not that important, but I thought you might want to find a way to not break the logos between the sites.

<img width="317" alt="screen shot 2018-07-06 at 12 05 12 pm" src="https://user-images.githubusercontent.com/52824/42373487-4f2911c8-8115-11e8-91a2-d81e110d6ccb.png">

**Comment by znarf** [comment] 2018-07-23 12:14
@kof we're effectively using the assets from Open Collective and the problem is that they're intended for another context (position, size, background).

If this is a problem, what we can do is host a logo in the "Back Your Stack" repository, we've already done that for 4 projects, see: https://github.com/opencollective/backyourstack/tree/master/src/static/img/profile

Should we do that for JSS?

**Comment by kof** [comment] 2018-07-23 12:16
Thats one way, another one would  be to ask user to upload 2 types of logos. And another one to use designs which work with all logo types. (needs some alignment between projects)

**Comment by znarf** [comment] 2018-07-23 12:31
In the _Back Your Stack_ context, the problem is that the logo is gonna be rounded. @cuiki do you have something to propose?

**Comment by znarf** [comment] 2018-07-23 13:55
@cuiki can you do the JSS one?

**Comment by cuiki** [comment] 2018-07-23 13:55
Yeah for sure. I'll get it to you in a bit.

**Comment by cuiki** [comment] 2018-07-24 04:46
Hi @kof, I'm not sure if this version faithfully represents your logo, since it already have a container within. The new design patterns on Open Collective use a squared profile pic for all of them. In your case the container will probably make that look weird. Is there an alternative for ir or should I leave it as the attached example?

![profile-pic-jss](https://user-images.githubusercontent.com/981188/43117426-5dc58b42-8ed2-11e8-96c1-485fdf64a283.png)

@znarf, the assets for that are in the issue referenced in my first response.

— https://www.dropbox.com/s/j379natubmkaen9/profile-pic-jss.png?dl=0
— https://www.dropbox.com/s/ewej8bex4776kfv/bg-cover-jss.jpg?dl=0

**Comment by kof** [comment] 2018-07-24 07:40
Hi,

It looks a bit weird tbh, but if its the only way to make it look ok on open collective right now, I guess it would be a workaround)

**Comment by znarf** [comment] 2018-07-25 12:13
Closing the issue.

We'll track our progress on the Open Collective logo specification strategy here: https://github.com/opencollective/opencollective/issues/1185

In the meantime, for anyone having logo issues on Back Your Stack, ping us or open a PR similar to this commit:
https://github.com/opencollective/backyourstack/commit/870d54ab6ec8f46afa0a24e35a16a13f9df35ca0

**Closed** 2018-07-25 12:14 UTC
